server:
  port: 9092
spring:
  kafka:
    producer:
      bootstrap-servers: 192.168.238.131:9092,192.168.238.132:9092,192.168.238.133:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer