# kubectl apply -f 01.yaml
# 修改host文件
# kubectl get svc -n ingress-nginx
# curl http://www1.atguigu.com:31685/
# kubectl delete -f 01.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 2
  template:
  metadata:
    labels:
      name: nginx1
  spec:
    containers:
    - name: nginx1
      image: wangyanglinux/myapp:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: nginx1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress1
spec:
  rules:
    - host: www1.atguigu.com
      http:
        paths:
        - path: /
          backend:
            serviceName: svc-1
            servicePort: 80