server:
  port: 8082
spring:
  application:
    name: dm-user-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0    #设置Sleuth的抽样收集概率
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true
dm-user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eureka:
    enabled: true
logging:
  level:
    root: info