spring:
  application:
    name: dm-base-provider
  datasource:
    url: jdbc:mysql://192.168.238.147:3306/dm_base?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
# 发往 ZipKin Server 的配置
#  zipkin:
#    base-url: http://localhost:7700
  rabbitmq:
    host: 192.168.238.147
    port: 5672
    username: admin
    password: 123456
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    database: 0
    host: 192.168.238.131
    port: 6379
    #    password: 123456
    timeout: 3000
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka
server:
  port: 7002
moduleName: dm-base-provider
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml