# 检测探针——存活检测
# kubectl create -f xxx.yaml
# kubectl get pod -w    =>  READY=1/1   STATUS=Running    RESTART=0
# 将容器内 nginx 端口由 80 改为 8080
# kubectl get pod -w    =>  READY=1/1   STATUS=Running    RESTART=3
apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp
spec:
  containers:
  - name: nginx
    image: hub.atguigu.com/library/myapp:v1
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      tcpSocket:
        port: 80
      periodSeconds: 3