server:
  port: 7201
spring:
  application:
    name: dm-item-consumer
  kafka:
    producer:
      retries: 0
      #batch-size: 16384 # 每次批量发送消息的数量
      bootstrap-servers: 192.168.238.131:9092,192.168.238.132:9092,192.168.238.133:9092
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 序列化设置
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # 同上
    listener:
      poll-timeout: 10000
  # 发往 ZipKin Server 的配置
  #  zipkin:
  #    base-url: http://localhost:7700
  rabbitmq:
    host: 192.168.238.147
    port: 5672
    username: admin
    password: 123456
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    database: 0
    host: 192.168.238.131
    port: 6379
    #    password: 123456
    timeout: 3000
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
moduleName: dm-item-consumer
