server:
  port: 8080
spring:
  application:
    name: dm-user-provider
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0    #设置Sleuth的抽样收集概率
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
logging:
  level:
    root: info