# kubectl apply -f 02_Headless_Service.yaml
# kubectl get svc
# kubectl get pod -n kube-system -o wide        ## 查看 coredns 的ip = 10.96.0.10
# yum -y install bind-utils
# dig -t A myapp-headless.default.svc.cluster.local. @10.96.0.10
apiVersion: v1
kind: Service
metadata:
  name: myapp-headless
  namespace: default
spec:
  selector:
    app: myapp
  clusterIP: "None"
  ports:
  - port: 80
    targetPort: 80