# kubectl apply -f 03_NodePort.yaml
# kubectl get pod -o wide
# kubectl get svc
# curl http://nodeIP:nodePort/            ## 将 内部服务 暴露给外部
# netstat -anpt | grep nodePort
# iptables -t nat -nvl KUBE-NODEPORTS     ## 查询流程: iptables 代理（旧）
# ipvsadm -Ln                             ## 查询流程: ipvs 代理（现在）
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 80