server:
  port: 7776
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7776/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: 0.49
spring:
  security:
    user:
      name: root
      password: 123456
      roles: SUPERUSER