/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdk_wangwenjun_chapter4_c04_jni_Hello */

#ifndef _Included_com_jdk_wangwenjun_chapter4_c04_jni_Hello
#define _Included_com_jdk_wangwenjun_chapter4_c04_jni_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdk_wangwenjun_chapter4_c04_jni_Hello
 * Method:    hi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jdk_wangwenjun_chapter4_c04_1jni_Hello_hi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
